import { Incident, Runbook, MemoryEntry, SimilarIncident } from "@/types";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000);
const minsAgo = (m: number) => new Date(now.getTime() - m * 60000);
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);

export const mockIncidents: Incident[] = [
  {
    id: "INC-1042",
    title: "Production API Latency Spike — p99 >8s",
    description:
      "Production API response times increased dramatically. P99 latency jumped from 180ms to 8.2 seconds. Affecting all checkout and payment endpoints. Customer-facing error rate at 12%. Revenue impact estimated at $45k/min.",
    service: "payments-api",
    severity: "critical",
    status: "investigating",
    createdAt: minsAgo(45),
    updatedAt: minsAgo(5),
    affectedUsers: 142000,
    affectedRegions: ["us-east-1", "eu-west-1"],
    tags: ["latency", "payments", "database", "p99"],
    assignee: "Sarah Chen",
    team: "Platform Engineering",
    timeline: [
      {
        id: "t1",
        timestamp: minsAgo(47),
        type: "detection",
        title: "Alert fired: p99 latency > 2000ms",
        description: "PagerDuty alert fired. Datadog detected p99 latency crossing 2s threshold on payments-api.",
        automated: true,
      },
      {
        id: "t2",
        timestamp: minsAgo(43),
        type: "investigation",
        title: "On-call engineer paged",
        description: "Sarah Chen acknowledged incident. Beginning triage.",
        author: "Sarah Chen",
      },
      {
        id: "t3",
        timestamp: minsAgo(38),
        type: "ai_insight",
        title: "IncidentIQ Analysis Complete",
        description: "AI identified 94% probability: PostgreSQL connection pool exhaustion on payments-db-primary. Similar to INC-891 (3 months ago).",
        automated: true,
      },
      {
        id: "t4",
        timestamp: minsAgo(30),
        type: "escalation",
        title: "Database team escalated",
        description: "DB team lead Mark Torres paged. Connection pool showing 100% utilization.",
        author: "Sarah Chen",
      },
      {
        id: "t5",
        timestamp: minsAgo(15),
        type: "mitigation",
        title: "Connection pool increased",
        description: "Increased max_connections from 100 to 200. Latency beginning to recover.",
        author: "Mark Torres",
      },
    ],
  },
  {
    id: "INC-1041",
    title: "Redis Cache Cluster Failover — EU Region",
    description:
      "Redis primary node in eu-west-1 failed. Automatic failover to replica triggered but caused 3-minute write outage. Session data for 28k users invalidated.",
    service: "session-store",
    severity: "high",
    status: "mitigating",
    createdAt: hoursAgo(2),
    updatedAt: minsAgo(20),
    affectedUsers: 28000,
    affectedRegions: ["eu-west-1"],
    rootCause: "Redis primary OOM due to uncontrolled key growth — TTL not set on analytics keys",
    tags: ["redis", "cache", "failover", "eu"],
    assignee: "Alex Kumar",
    team: "Infrastructure",
    timeline: [
      {
        id: "t1",
        timestamp: hoursAgo(2),
        type: "detection",
        title: "Redis primary node unresponsive",
        description: "Health check failed. Automatic failover initiated.",
        automated: true,
      },
      {
        id: "t2",
        timestamp: hoursAgo(1.9),
        type: "investigation",
        title: "OOM killer logs found",
        description: "Redis consumed 99.8% of available memory. OOM killer terminated process.",
        author: "Alex Kumar",
      },
    ],
  },
  {
    id: "INC-1040",
    title: "Kubernetes Pod CrashLoopBackOff — ML Inference",
    description:
      "ML inference service pods entering CrashLoopBackOff. Model serving returning 503. Recommendation engine down.",
    service: "ml-inference",
    severity: "high",
    status: "active",
    createdAt: hoursAgo(1),
    updatedAt: minsAgo(10),
    affectedUsers: 890000,
    tags: ["kubernetes", "ml", "crashloop", "inference"],
    assignee: "Priya Sharma",
    team: "ML Platform",
    timeline: [
      {
        id: "t1",
        timestamp: hoursAgo(1),
        type: "detection",
        title: "CrashLoopBackOff detected",
        description: "Kubernetes pod restarts exceeded 5 in 10 minutes.",
        automated: true,
      },
    ],
  },
  {
    id: "INC-1039",
    title: "CDN Cache Poisoning — Static Assets",
    description: "Stale 404 responses being cached and served for valid static assets after deployment.",
    service: "cdn-cloudflare",
    severity: "medium",
    status: "resolved",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(20),
    resolvedAt: hoursAgo(20),
    mttr: 47,
    rootCause: "Cache-Control headers missing max-age on origin. Cloudflare cached 404 responses.",
    resolution: "Purged CDN cache globally. Added proper Cache-Control headers to nginx config.",
    tags: ["cdn", "cache", "deployment", "cloudflare"],
    assignee: "James Liu",
    team: "Web Platform",
    timeline: [],
  },
  {
    id: "INC-1038",
    title: "Database Migration Timeout — User Table",
    description: "Schema migration adding index on users table timed out after 30 minutes. Table locked, blocking all writes.",
    service: "user-service",
    severity: "critical",
    status: "resolved",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    resolvedAt: daysAgo(2),
    mttr: 78,
    rootCause: "ALTER TABLE acquired full table lock on 50M row table. Should have used pt-online-schema-change.",
    resolution: "Killed migration. Used pt-osc for zero-downtime migration. Completed in 22 minutes.",
    tags: ["database", "migration", "lock", "postgres"],
    assignee: "Mark Torres",
    team: "Data Engineering",
    timeline: [],
  },
  {
    id: "INC-1037",
    title: "S3 Bucket Policy Misconfiguration",
    description: "Accidentally public S3 bucket exposed internal API documentation for 2 hours.",
    service: "storage-s3",
    severity: "high",
    status: "postmortem",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    resolvedAt: daysAgo(5),
    mttr: 25,
    tags: ["security", "s3", "misconfiguration"],
    assignee: "Emily Rodriguez",
    team: "Security",
    timeline: [],
  },
  {
    id: "INC-1036",
    title: "Webhook Delivery Failures — Stripe Integration",
    description: "Stripe webhook processor failing silently. 3400 payment webhooks unprocessed over 6 hours.",
    service: "webhook-processor",
    severity: "critical",
    status: "resolved",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    resolvedAt: daysAgo(7),
    mttr: 180,
    rootCause: "Dead letter queue full. Worker threads blocked on database deadlock.",
    resolution: "Cleared DLQ. Fixed deadlock by adjusting transaction isolation level.",
    tags: ["webhooks", "stripe", "payments", "deadlock"],
    assignee: "Sarah Chen",
    team: "Platform Engineering",
    timeline: [],
  },
];

export const mockRunbooks: Runbook[] = [
  {
    id: "RB-001",
    title: "Database Connection Pool Exhaustion",
    service: "payments-api",
    owner: "Mark Torres",
    usageCount: 23,
    lastUpdated: daysAgo(3),
    confidenceScore: 97,
    tags: ["database", "postgres", "connection-pool", "latency"],
    content: "# Database Connection Pool Exhaustion Runbook\n\nUse when p99 latency spikes and DB connections are maxed out.",
    steps: [
      { id: "s1", order: 1, title: "Check connection pool status", description: "Query pg_stat_activity", command: "SELECT count(*), state FROM pg_stat_activity GROUP BY state;" },
      { id: "s2", order: 2, title: "Identify long-running queries", description: "Find blocking queries", command: "SELECT pid, now() - pg_stat_activity.query_start AS duration, query FROM pg_stat_activity WHERE state = 'active' ORDER BY duration DESC;" },
      { id: "s3", order: 3, title: "Kill idle connections", description: "Terminate idle connections", command: "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle' AND query_start < NOW() - INTERVAL '5 minutes';" },
    ],
    relatedIncidents: ["INC-1042", "INC-891"],
  },
  {
    id: "RB-002",
    title: "Redis OOM Recovery",
    service: "session-store",
    owner: "Alex Kumar",
    usageCount: 11,
    lastUpdated: daysAgo(7),
    confidenceScore: 91,
    tags: ["redis", "memory", "oom", "cache"],
    content: "# Redis Out of Memory Recovery",
    steps: [
      { id: "s1", order: 1, title: "Check memory usage", description: "Redis memory info", command: "redis-cli INFO memory" },
      { id: "s2", order: 2, title: "Find largest keys", description: "Scan for memory hogs", command: "redis-cli --bigkeys" },
    ],
    relatedIncidents: ["INC-1041"],
  },
  {
    id: "RB-003",
    title: "Kubernetes Pod CrashLoop Investigation",
    service: "kubernetes",
    owner: "Priya Sharma",
    usageCount: 34,
    lastUpdated: daysAgo(1),
    confidenceScore: 88,
    tags: ["kubernetes", "crashloop", "pods", "oom"],
    content: "# Kubernetes CrashLoopBackOff Runbook",
    steps: [
      { id: "s1", order: 1, title: "Get pod status", description: "Check pod events", command: "kubectl describe pod <pod-name> -n <namespace>" },
      { id: "s2", order: 2, title: "View crash logs", description: "Previous container logs", command: "kubectl logs <pod-name> --previous -n <namespace>" },
    ],
    relatedIncidents: ["INC-1040"],
  },
  {
    id: "RB-004",
    title: "CDN Cache Purge — Emergency",
    service: "cdn-cloudflare",
    owner: "James Liu",
    usageCount: 8,
    lastUpdated: daysAgo(14),
    confidenceScore: 99,
    tags: ["cdn", "cloudflare", "cache", "purge"],
    content: "# Emergency CDN Cache Purge",
    steps: [
      { id: "s1", order: 1, title: "Purge all cache", description: "Cloudflare global purge", command: "curl -X DELETE 'https://api.cloudflare.com/client/v4/zones/{zone_id}/purge_cache' \\\n  -H 'Authorization: Bearer {token}' \\\n  -H 'Content-Type: application/json' \\\n  --data '{\"purge_everything\":true}'" },
    ],
    relatedIncidents: ["INC-1039"],
  },
  {
    id: "RB-005",
    title: "S3 Bucket Security Lockdown",
    service: "storage-s3",
    owner: "Emily Rodriguez",
    usageCount: 5,
    lastUpdated: daysAgo(4),
    confidenceScore: 100,
    tags: ["s3", "security", "bucket", "policy"],
    content: "# S3 Security Incident Response",
    steps: [
      { id: "s1", order: 1, title: "Block public access immediately", description: "Disable all public access", command: "aws s3api put-public-access-block \\\n  --bucket <bucket-name> \\\n  --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true" },
    ],
    relatedIncidents: ["INC-1037"],
  },
  {
    id: "RB-006",
    title: "Stripe Webhook Processor Recovery",
    service: "webhook-processor",
    owner: "Sarah Chen",
    usageCount: 4,
    lastUpdated: daysAgo(6),
    confidenceScore: 85,
    tags: ["webhooks", "stripe", "queue", "dlq"],
    content: "# Stripe Webhook Recovery Runbook",
    steps: [],
    relatedIncidents: ["INC-1036"],
  },
];

export const mockMemoryEntries: MemoryEntry[] = [
  {
    id: "MEM-001",
    incidentId: "INC-891",
    service: "payments-api",
    date: daysAgo(92),
    rootCause: "PostgreSQL connection pool exhaustion during Black Friday traffic spike",
    resolution: "Increased max_connections, implemented PgBouncer connection pooler, added circuit breaker",
    severity: "critical",
    tags: ["database", "connection-pool", "postgres", "traffic-spike"],
  },
  {
    id: "MEM-002",
    incidentId: "INC-743",
    service: "session-store",
    date: daysAgo(180),
    rootCause: "Redis OOM — analytics pipeline writing unbounded keys without TTL",
    resolution: "Set TTL on all analytics keys, enabled maxmemory-policy allkeys-lru, added memory alerts",
    severity: "high",
    tags: ["redis", "oom", "ttl", "analytics"],
  },
  {
    id: "MEM-003",
    incidentId: "INC-612",
    service: "ml-inference",
    date: daysAgo(210),
    rootCause: "Model artifact corrupted during blue-green deployment. Pods crashing on model load.",
    resolution: "Rolled back to previous model version. Added model validation step to deployment pipeline.",
    severity: "high",
    tags: ["ml", "kubernetes", "deployment", "model-corruption"],
  },
  {
    id: "MEM-004",
    incidentId: "INC-558",
    service: "cdn-cloudflare",
    date: daysAgo(270),
    rootCause: "Missing Cache-Control headers caused CDN to cache error responses",
    resolution: "Added explicit Cache-Control headers. Cloudflare page rule to never cache 4xx/5xx.",
    severity: "medium",
    tags: ["cdn", "cache", "headers", "cloudflare"],
  },
  {
    id: "MEM-005",
    incidentId: "INC-445",
    service: "user-service",
    date: daysAgo(365),
    rootCause: "Full table lock from ALTER TABLE on production database with 50M+ rows",
    resolution: "Used pt-online-schema-change for zero-downtime schema migrations going forward",
    severity: "critical",
    tags: ["database", "migration", "lock", "postgres"],
  },
];

export const mockSimilarIncidents: SimilarIncident[] = [
  {
    id: "INC-891",
    title: "Payment API Latency — Black Friday",
    service: "payments-api",
    similarity: 94,
    rootCause: "PostgreSQL connection pool exhaustion",
    resolution: "Increased pool size + PgBouncer",
    date: daysAgo(92),
    resolutionTime: 34,
  },
  {
    id: "INC-756",
    title: "Checkout API Timeout Storm",
    service: "payments-api",
    similarity: 78,
    rootCause: "Downstream dependency timeout causing thread pool saturation",
    resolution: "Added circuit breaker + increased timeout headroom",
    date: daysAgo(145),
    resolutionTime: 52,
  },
  {
    id: "INC-634",
    title: "API Gateway 504 Cascade",
    service: "api-gateway",
    similarity: 65,
    rootCause: "Database query degradation causing upstream timeout cascade",
    resolution: "Query optimization + index addition + connection pooling",
    date: daysAgo(198),
    resolutionTime: 89,
  },
];

export const analyticsData = {
  incidentFrequency: [
    { month: "Jan", critical: 2, high: 5, medium: 8, low: 12 },
    { month: "Feb", critical: 1, high: 4, medium: 6, low: 10 },
    { month: "Mar", critical: 3, high: 7, medium: 9, low: 14 },
    { month: "Apr", critical: 1, high: 3, medium: 5, low: 9 },
    { month: "May", critical: 2, high: 6, medium: 8, low: 11 },
    { month: "Jun", critical: 2, high: 4, medium: 6, low: 8 },
  ],
  mttrTrend: [
    { month: "Jan", mttr: 142 },
    { month: "Feb", mttr: 118 },
    { month: "Mar", mttr: 95 },
    { month: "Apr", mttr: 87 },
    { month: "May", mttr: 72 },
    { month: "Jun", mttr: 58 },
  ],
  serviceReliability: [
    { service: "payments-api", uptime: 99.87 },
    { service: "user-service", uptime: 99.94 },
    { service: "ml-inference", uptime: 98.92 },
    { service: "session-store", uptime: 99.71 },
    { service: "cdn-cloudflare", uptime: 99.99 },
    { service: "webhook-processor", uptime: 99.23 },
  ],
  rootCauseDistribution: [
    { cause: "Database Issues", value: 32, fill: "#3B82F6" },
    { cause: "Infrastructure", value: 24, fill: "#8B5CF6" },
    { cause: "Deployment", value: 18, fill: "#F59E0B" },
    { cause: "Third-party", value: 14, fill: "#22C55E" },
    { cause: "Code Bugs", value: 8, fill: "#EF4444" },
    { cause: "Configuration", value: 4, fill: "#06B6D4" },
  ],
  memoryReuseRate: [
    { week: "W1", reuse: 42 },
    { week: "W2", reuse: 51 },
    { week: "W3", reuse: 58 },
    { week: "W4", reuse: 67 },
    { week: "W5", reuse: 71 },
    { week: "W6", reuse: 79 },
    { week: "W7", reuse: 83 },
    { week: "W8", reuse: 88 },
  ],
  aiAccuracy: [
    { month: "Jan", accuracy: 71 },
    { month: "Feb", accuracy: 74 },
    { month: "Mar", accuracy: 79 },
    { month: "Apr", accuracy: 83 },
    { month: "May", accuracy: 88 },
    { month: "Jun", accuracy: 92 },
  ],
  teamPerformance: [
    { team: "Platform Eng", incidents: 34, avgMttr: 52, resolved: 34 },
    { team: "Data Eng", incidents: 22, avgMttr: 78, resolved: 21 },
    { team: "ML Platform", incidents: 18, avgMttr: 94, resolved: 17 },
    { team: "Security", incidents: 12, avgMttr: 31, resolved: 12 },
    { team: "Web Platform", incidents: 28, avgMttr: 45, resolved: 28 },
  ],
};

export const mockStats = {
  activeIncidents: 3,
  criticalAlerts: 1,
  mttr: 58,
  memoryMatches: 1284,
  aiAccuracy: 92,
  resolvedToday: 7,
};
