import { NextRequest } from "next/server";
import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || "",
});

export async function POST(req: NextRequest) {
  try {
    const { incident } = await req.json();

    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      max_tokens: 6000,
      messages: [
        {
          role: "user",
          content: `Generate a professional, blameless postmortem for this production incident. Follow Google SRE postmortem best practices.

**Incident:** ${incident.title}
**Duration:** ${incident.duration} minutes  
**Service:** ${incident.service}
**Severity:** ${incident.severity}
**Impact:** ${incident.impact}
**Root Cause:** ${incident.rootCause}
**Resolution:** ${incident.resolution}
**Description:** ${incident.description}

Generate a complete postmortem in markdown format:

# 🔴 Incident Postmortem: ${incident.title}

**Date:** ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
**Severity:** ${incident.severity?.toUpperCase()}
**Status:** Resolved
**Authors:** [Incident Response Team]
**Review Date:** [One week from incident]

---

## Executive Summary
[2-3 sentences for leadership — what happened, impact, and resolution]

## Impact Analysis
- **Duration:** ${incident.duration} minutes
- **Users Affected:** [estimate]
- **Revenue Impact:** [estimate]
- **SLA Breach:** [yes/no and severity]
- **Regions Affected:** [list]

## Incident Timeline
| Time | Event | Who |
|------|-------|-----|
[Fill in chronological events]

## Root Cause Analysis

### Primary Root Cause
[Technical deep-dive]

### 5 Whys Analysis
1. Why did [symptom] occur? → Because [cause 1]
2. Why did [cause 1] occur? → Because [cause 2]
3. Why did [cause 2] occur? → Because [cause 3]
4. Why did [cause 3] occur? → Because [cause 4]
5. Why did [cause 4] occur? → Because [root cause]

## Contributing Factors
- [Factor 1]
- [Factor 2]

## Resolution Steps
[Numbered steps taken to resolve]

## Lessons Learned
### What went well
- [Item]

### What could be improved
- [Item]

## Action Items
| Priority | Action Item | Owner | Due Date | Status |
|----------|-------------|-------|----------|--------|
| P1 | | | | Open |
| P2 | | | | Open |

## Prevention Measures
[How to prevent recurrence]

---
*This postmortem was auto-generated by IncidentIQ AI. Please review and update before sharing.*`,
        },
      ],
    });

    const text = response.content[0].type === "text" ? response.content[0].text : "";
    return Response.json({ postmortem: text });
  } catch (err) {
    return Response.json({ error: "Failed to generate postmortem" }, { status: 500 });
  }
}
